### ISSUE TITLE
Not working on Sublime Text 3?

### ISSUE THREAD

**Issue by jadjoubran** [ayamflow/AngularInject#1]
I couldn't find the command and the hotkey didn't work
Let me know if you need more info
Thanks!

**Comment by mikedigital** [comment]
I will also just bump this that this does not work for Sublime Text 3.

**Comment by ayamflow** [comment]
As the readme says, this is a *Sublime Text 2 Plugin*.
Moreover, I developed this for Angular 1 which is now pretty outdated.

I'm actually going to update the package control list to reflect this.

**Comment by mikedigital** [comment]
I know. I didn't know if a post a year and a half after the last post would have lit a fire so to speak. I just started writing Angular 2 and don't want to leave Sublime Text. I took my chances in hopes this would work.

**Comment by ayamflow** [comment]
Sorry! I actually developed this when only ST2 was around and didn't think it would be installable on ST3. Also totally missed this issue in 2015...
